"use client";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Spiderware (https://sketchfab.com/Spiderware)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spider-man-spider-man-no-way-home-2cb11e591cc44357bffc6e23931a78e2
Title: Spider-man (Spider-man: No way Home)
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function SpiderMan(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/spider-man_spider-man_no_way_home.glb"
  );
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    actions[names[17]].reset().fadeIn(0.2).play();
  
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <ambientLight intensity={2} color={"#fff"} />
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={4}>
          <group
            name="Spider-man_(Integrated_Suit)fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature" scale={100}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_149"
                      geometry={nodes.Object_149.geometry}
                      material={materials.SpiderMan_web02}
                      skeleton={nodes.Object_149.skeleton}
                    />
                    <skinnedMesh
                      name="Object_151"
                      geometry={nodes.Object_151.geometry}
                      material={materials.hero_spiderman01_s08_02}
                      skeleton={nodes.Object_151.skeleton}
                    />
                    <skinnedMesh
                      name="Object_153"
                      geometry={nodes.Object_153.geometry}
                      material={materials.hero_spiderman01_s08_01}
                      skeleton={nodes.Object_153.skeleton}
                    />
                    <skinnedMesh
                      name="Object_155"
                      geometry={nodes.Object_155.geometry}
                      material={materials.hero_spiderman01_s08_03}
                      skeleton={nodes.Object_155.skeleton}
                    />
                    <skinnedMesh
                      name="Object_157"
                      geometry={nodes.Object_157.geometry}
                      material={materials.SpiderMan_web02}
                      skeleton={nodes.Object_157.skeleton}
                    />
                    <skinnedMesh
                      name="Object_159"
                      geometry={nodes.Object_159.geometry}
                      material={materials.manhole}
                      skeleton={nodes.Object_159.skeleton}
                    />
                    <skinnedMesh
                      name="Object_161"
                      geometry={nodes.Object_161.geometry}
                      material={materials.hero_spiderman01_s08_wp}
                      skeleton={nodes.Object_161.skeleton}
                    />
                    <group
                      name="Object_148"
                      position={[100, 4, 0]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_150"
                      position={[0, 4, 13.289]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_152"
                      position={[0, 4, 13.289]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_154"
                      position={[0, 4, 13.289]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_156"
                      position={[-100, 4, 0]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_158"
                      position={[-266.612, 4, 0.478]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_160"
                      position={[0, 136.869, -9.593]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={80}
                    />
                  </group>
                </group>
                <group
                  name="spider_wp003"
                  position={[100, 4, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="hero_spiderman01_s08_02"
                  position={[0, 4, 13.289]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="hero_spiderman01_s08_01"
                  position={[0, 4, 13.289]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="hero_spiderman01_s08_03"
                  position={[0, 4, 13.289]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="spider_wp02"
                  position={[-100, 4, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="manhole"
                  position={[-266.612, 4, 0.478]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="hero_spiderman01_s08_wp"
                  position={[0, 136.869, -9.593]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={80}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/spider-man_spider-man_no_way_home.glb");
